---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: default
  labels:
    app: wordpress
    func: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
      func: database
  template:
    metadata:
      labels:
        app: wordpress
        func: database
    spec:
      containers:
        - name: mariadb
          image: bitnami/mariadb:10.3
          ports:
            - name: db-port
              containerPort: 3306
          env:
            - name: MARIADB_USER
              value: wordpress
            - name: MARIADB_DATABASE
              value: wordpress
            - name: MARIADB_PASSWORD
              value: secretmariadbpassword
            - name: MARIADB_ROOT_PASSWORD
              value: moresecretmariadbpassword
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: default
  labels:
    app: wordpress
    func: database
spec:
  selector:
    app: wordpress
    func: database
  ports:
    - port: 3306
      targetPort: db-port
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: default
  labels:
    app: wordpress
    func: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
      func: frontend
  template:
    metadata:
      labels:
        app: wordpress
        func: frontend
    spec:
      containers:
        - name: wordpress
          image: bitnami/wordpress:4.9.8
          ports:
            - name: wordpress
              containerPort: 80
          env:
            - name: MARIADB_HOST
              value: mariadb
            - name: MARIADB_PORT_NUMBER
              value: "3306"
            - name: WORDPRESS_DATABASE_USER
              value: wordpress
            - name: WORDPRESS_DATABASE_PASSWORD
              value: secretmariadbpassword
            - name: WORDPRESS_DATABASE_NAME
              value: wordpress
            - name: WORDPRESS_BLOG_NAME
              value: Metsi Kubernetes Course
            - name: WORDPRESS_PASSWORD
              value: youwouldneverguess
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: default
  labels:
    app: wordpress
    func: frontend
spec:
  selector:
    app: wordpress
    func: frontend
  ports:
    - name: wordpress
      port: 80
      targetPort: 80
  type: LoadBalancer
